spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ENC(DJV5MsDLF/6adraw4pj3ZQ==)
    url: jdbc:h2:file:./pc-db
    username: dzabic
    initialization-mode: never
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

jasypt:
  encryptor:
    password: goveed20

server:
  port: 0
  servlet:
    context-path: /api
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: src/main/resources/paymentConcentrator.p12
    key-alias: paymentConcentrator
    key-store-password: goveda2020
    # client-auth: need
    trust-store: src/main/resources/paymentConcentratorTruststore.jks
    trust-store-password: goveda2020
    trust-store-type: JKS

---
spring:
  profiles: zone1
  cloud:
    consul:
      discovery:
        instanceZone: zone1

---
spring:
  profiles: zone2
  cloud:
    consul:
      discovery:
        instanceZone: zone2
