spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ENC(DJV5MsDLF/6adraw4pj3ZQ==)
    url: jdbc:h2:file:./pc-db
    username: dzabic
    initialization-mode: never
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    password: ENC(ADCd7T3iSrmU4tUdsL9RYu4ALBP8A20D)
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    username: goveed20@gmail.com

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

jasypt:
  encryptor:
    password: goveed20

---
spring:
  profiles: zone1
  cloud:
    consul:
      discovery:
        instanceZone: zone1

---
spring:
  profiles: zone2
  cloud:
    consul:
      discovery:
        instanceZone: zone2
