spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ENC(DJV5MsDLF/6adraw4pj3ZQ==)
    url: jdbc:h2:file:./pc-db
    username: dzabic
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  cloud:
    consul:
      discovery:
        instance-id: "${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}"

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonRequestLoggingFilter:
              DEBUG

jasypt:
  encryptor:
    password: goveed20

server:
  port: 0
  servlet:
    context-path: /api

---
spring:
  profiles: zone1
  cloud:
    consul:
      discovery:
        instanceZone: zone1

---
spring:
  profiles: zone2
  cloud:
    consul:
      discovery:
        instanceZone: zone2
