spring:
  application:
    name: literary-association
  datasource:
    driver-class-name: org.h2.Driver
    password: ENC(DJV5MsDLF/6adraw4pj3ZQ==)
    url: jdbc:h2:~/database
    username: dzabic
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

server:
  servlet:
    context-path: /api
  port: 9090

jasypt:
  encryptor:
    password: goveed20
