version: '2'
services:

  consul1:
    image: consul
    ports:
     - "8500:8500"
    environment:
     - CONSUL_BIND_INTERFACE=eth0
    networks:
      static-network:
        ipv4_address: 172.20.128.2

  consul2:
     image: consul
     ports:
      - "8501:8500"
     environment:
      - CONSUL_BIND_INTERFACE=eth0
     command: "agent -dev -join=172.20.128.2"
     networks:
       static-network:
         ipv4_address: 172.20.128.3
     depends_on:
       - consul1

  consul3:
     image: consul
     ports:
      - "8502:8500"
     environment:
      - CONSUL_BIND_INTERFACE=eth0
     command: "agent -dev -join=172.20.128.2"
     networks:
       static-network:
         ipv4_address: 172.20.128.4
     depends_on:
       - consul2

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.28.5.0/24
